[workspace]
members = [
    "github-stars",
    "json-to-yaml",
    "reddit-pagination",
    "log-level",
    "regex-scrubbing",
    "grocery-notifications",
    "grocery-notifications-simple",
    "summing-integers",
    "incremental-average",
    "json-array-expansion",
]

[profile.release]
lto = true
