[workspace]
members = [
    "github-stars",
    "json-to-yaml",
    "reddit-pagination",
    "log-level",
    "regex-scrubbing",
    "grocery-notifications",
    "summing-integers",
]

[profile.release]
lto = true
