[package]
name = "smartmodule-json"
version = "0.1.0"
authors = ["Fluvio Contributors <team@fluvio.io>"]
edition = "2021"

[lib]
crate-type = ['cdylib']

[dependencies]
fluvio-smartmodule = { version = "0.2" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
