[package]
name = "summing-integers"
version = "0.0.0"
authors = ["Fluvio Contributors <team@fluvio.io>"]
edition = "2018"
publish = false

[lib]
crate-type = ['cdylib']

[dependencies]
fluvio-smartmodule = { version = "0.1.0" }
