name: CI

permissions:
  contents: read

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  main:
    name: ${{ matrix.task.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [stable]
        task:
          - name: Rustfmt
            run: cargo fmt -- --check
          - name: Clippy
            run: cargo clippy
          - name: Build
            run: cargo build
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust ${{ matrix.rust }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          override: true
          target: wasm32-unknown-unknown

      - uses: Swatinem/rust-cache@v1

      - name: ${{ matrix.task.name }}
        run: ${{ matrix.task.run }}
